// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PontosTuristicos.Infrastructure.Data;

#nullable disable

namespace PontosTuristicos.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260310221116_AlterarProcedureParaDapper")]
    partial class AlterarProcedureParaDapper
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PontosTuristicos.Domain.Entities.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoSigla");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoSigla = "SP",
                            Nome = "São Paulo"
                        },
                        new
                        {
                            Id = 2,
                            EstadoSigla = "RJ",
                            Nome = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 3,
                            EstadoSigla = "SP",
                            Nome = "Pompeia"
                        },
                        new
                        {
                            Id = 4,
                            EstadoSigla = "SP",
                            Nome = "Tupã"
                        });
                });

            modelBuilder.Entity("PontosTuristicos.Domain.Entities.Estado", b =>
                {
                    b.Property<string>("Sigla")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Sigla");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Sigla = "SP",
                            Nome = "São Paulo"
                        },
                        new
                        {
                            Sigla = "RJ",
                            Nome = "Rio de Janeiro"
                        },
                        new
                        {
                            Sigla = "MG",
                            Nome = "Minas Gerais"
                        },
                        new
                        {
                            Sigla = "PR",
                            Nome = "Paraná"
                        },
                        new
                        {
                            Sigla = "SC",
                            Nome = "Santa Catarina"
                        },
                        new
                        {
                            Sigla = "RS",
                            Nome = "Rio Grande do Sul"
                        });
                });

            modelBuilder.Entity("PontosTuristicos.Domain.Entities.PontoTuristico", b =>
                {
                    b.Property<int>("IdPontosTuristicos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPontosTuristicos"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CEP")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdCidade")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdPontosTuristicos");

                    b.HasIndex("IdCidade");

                    b.ToTable("PontosTuristicos");

                    b.HasData(
                        new
                        {
                            IdPontosTuristicos = 1,
                            Ativo = true,
                            CEP = "01310200",
                            DataInclusao = new DateTime(2026, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Famoso museu na Avenida Paulista com arquitetura icônica.",
                            IdCidade = 1,
                            Localizacao = "Avenida Paulista, 1578",
                            Nome = "Museu de Arte de São Paulo (MASP)"
                        },
                        new
                        {
                            IdPontosTuristicos = 2,
                            Ativo = true,
                            CEP = "22241120",
                            DataInclusao = new DateTime(2026, 3, 2, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Estátua Jesus Cristo, símbolo do Rio de Janeiro.",
                            IdCidade = 2,
                            Localizacao = "Parque Nacional da Tijuca",
                            Nome = "Cristo Redentor"
                        },
                        new
                        {
                            IdPontosTuristicos = 3,
                            Ativo = true,
                            CEP = "17580000",
                            DataInclusao = new DateTime(2026, 3, 5, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Um museu sobre a evolução dos sistemas e hardware.",
                            IdCidade = 3,
                            Localizacao = "Centro, perto da praça principal",
                            Nome = "Museu de Tecnologia"
                        },
                        new
                        {
                            IdPontosTuristicos = 4,
                            Ativo = true,
                            CEP = "17600380",
                            DataInclusao = new DateTime(2026, 3, 8, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Bela praça com a igreja Matriz.",
                            IdCidade = 4,
                            Localizacao = "Centro, perto da Câmara Municipal",
                            Nome = "Praça da Bandeira"
                        });
                });

            modelBuilder.Entity("PontosTuristicos.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("PontosTuristicos.Domain.Entities.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoSigla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("PontosTuristicos.Domain.Entities.PontoTuristico", b =>
                {
                    b.HasOne("PontosTuristicos.Domain.Entities.Cidade", "Cidade")
                        .WithMany("PontosTuristicos")
                        .HasForeignKey("IdCidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("PontosTuristicos.Domain.Entities.Cidade", b =>
                {
                    b.Navigation("PontosTuristicos");
                });

            modelBuilder.Entity("PontosTuristicos.Domain.Entities.Estado", b =>
                {
                    b.Navigation("Cidades");
                });
#pragma warning restore 612, 618
        }
    }
}
